[package]
name = "hmir-token"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonwebtoken = "8"
serde = {version = "1.0", features = ["derive"] }
log4rs = "1.2.0"
log = "0.4.17"