[package]
name = "hmir-ceph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ceph-rust = "0.1.17"
libc = "0.2.138"
ceph = "3.2.5"
log4rs = "1.2.0"
log = "0.4.17"
