refresh_rate: 30 seconds
appenders:
  stdout:
    kind: file
    path: "/var/log/hmir.log"
    encoder:
      pattern: "{d(%+)} [{f}:{L}] {h({l})} {M}:{m}{n}"

root:
  level: info
  appenders:
    - stdout
